apiVersion: v1
kind: api
metadata:
  plugin:
    aaa:
      namespace: add
spec:
  cluster: main
  descr: Main namespace
  ns: main
  paths: {{}}
---
apiVersion: v1
kind: api
metadata:
  plugin:
    cache:
      config: add
spec:
  name: {name}
  nvme_node_disks_count: {nvme_node_disks_count}
  lvol_r_cache_size_in_mib: {r_cache_size_in_mib}
  lvol_rw_cache_size_in_mib: {rw_cache_size_in_mib}
  nvme_bdev_retry_count: -1
  nvme_ctrlr_loss_timeout_sec: 60
  nvme_fast_io_fail_timeout_sec: 30
  raid_bdev_retry_count: -1
  raid_ctrlr_loss_timeout_sec: 60
  raid_fast_io_fail_timeout_sec: 30
  raid_level: {raid_level}
---
apiVersion: v1
kind: api
metadata:
  plugin:
    cache:
      pool: add
spec:
  config: {name}
  descr: {description}
  labels: {labels}
  name: {name}
  node_ips: {node_ips}
  s3_buckets: {s3_bucket_names}
  disks_count: {nvme_node_disks_count}
  volumes_count: {max_volumes_count}
  r_cache_size_in_mib: {r_cache_size_in_mib}
  rw_cache_size_in_mib: {rw_cache_size_in_mib}
